// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuSzLmlu6dX896h8mxB9PU14Ezi4oIdtg',
    appId: '1:56780659497:web:4a7a89ef99d829b1a5f538',
    messagingSenderId: '56780659497',
    projectId: 'marathamangal-bb6c9',
    authDomain: 'marathamangal-bb6c9.firebaseapp.com',
    storageBucket: 'marathamangal-bb6c9.appspot.com',
    measurementId: 'G-SBT8ES003D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUCXXuV2kivYw3dwCxQ6Zl_lvaCKVRuY',
    appId: '1:56780659497:android:7917249df280c300a5f538',
    messagingSenderId: '56780659497',
    projectId: 'marathamangal-bb6c9',
    storageBucket: 'marathamangal-bb6c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZCraxlJxCgQrIpveAt86gibjnTodBqY',
    appId: '1:56780659497:ios:a219d88c952232e4a5f538',
    messagingSenderId: '56780659497',
    projectId: 'marathamangal-bb6c9',
    storageBucket: 'marathamangal-bb6c9.appspot.com',
    iosClientId: '56780659497-0itfic0l7pcccch008dcoopmv278hrbp.apps.googleusercontent.com',
    iosBundleId: 'com.marathamangal.marathamangaluserapp',
  );
}
